export const genres = [
    { id: "1", name: "Artbook" },
    { id: "2", name: "Cartoon" },
    { id: "3", name: "Comic" },
    { id: "4", name: "Doujinshi" },
    { id: "5", name: "Imageset" },
    { id: "6", name: "Manga" },
    { id: "7", name: "Manhua" },
    { id: "8", name: "Manhwa" },
    { id: "9", name: "Webtoon" },
    { id: "10", name: "Western" },
    { id: "11", name: "4-Koma" },
    { id: "12", name: "Oneshot" },
    { id: "13", name: "Shoujo(G)" },
    { id: "14", name: "Shounen(B)" },
    { id: "15", name: "Josei(W)" },
    { id: "16", name: "Seinen(M)" },
    { id: "17", name: "Yuri(GL)" },
    { id: "18", name: "Yaoi(BL)" },
    { id: "19", name: "Bara(ML)" },
    { id: "20", name: "Kodomo(Kid)" },
    { id: "21", name: "Silver & Golden" },
    { id: "22", name: "Non-human" },
    { id: "23", name: "Gore" },
    { id: "24", name: "Bloody" },
    { id: "25", name: "Violence" },
    { id: "26", name: "Ecchi" },
    { id: "27", name: "Adult" },
    { id: "28", name: "Mature" },
    { id: "29", name: "Smut" },
    { id: "30", name: "Hentai" },
    { id: "31", name: "Action" },
    { id: "32", name: "Adaptation" },
    { id: "33", name: "Adventure" },
    { id: "34", name: "Age Gap" },
    { id: "35", name: "Aliens" },
    { id: "36", name: "Animals" },
    { id: "37", name: "Anthology" },
    { id: "38", name: "Beasts" },
    { id: "39", name: "Bodyswap" },
    { id: "40", name: "Boys" },
    { id: "41", name: "Cars" },
    { id: "42", name: "Cheating/Infidelity" },
    { id: "43", name: "Childhood Friends" },
    { id: "44", name: "College life" },
    { id: "45", name: "Comedy" },
    { id: "46", name: "Contest winning" },
    { id: "47", name: "Cooking" },
    { id: "48", name: "Crime" },
    { id: "49", name: "Crossdressing" },
    { id: "50", name: "Delinquents" },
    { id: "51", name: "Dementia" },
    { id: "52", name: "Demons" },
    { id: "53", name: "Drama" },
    { id: "54", name: "Dungeons" },
    { id: "55", name: "Emperor's daughter" },
    { id: "56", name: "Fantasy" },
    { id: "57", name: "Fan-Colored" },
    { id: "58", name: "Fetish" },
    { id: "59", name: "Full Color" },
    { id: "60", name: "Game" },
    { id: "61", name: "Gender Bender" },
    { id: "62", name: "Genderswap" },
    { id: "63", name: "Ghosts" },
    { id: "64", name: "Girls" },
    { id: "65", name: "Gyaru" },
    { id: "66", name: "Harem" },
    { id: "67", name: "Harlequin" },
    { id: "68", name: "Historical" },
    { id: "69", name: "Horror" },
    { id: "70", name: "Incest" },
    { id: "71", name: "Isekai" },
    { id: "72", name: "Kids" },
    { id: "73", name: "Magic" },
    { id: "74", name: "Magical Girls" },
    { id: "75", name: "Martial Arts" },
    { id: "76", name: "Mecha" },
    { id: "77", name: "Medical" },
    { id: "78", name: "Military" },
    { id: "79", name: "Monster Girls" },
    { id: "80", name: "Monsters" },
    { id: "81", name: "Music" },
    { id: "82", name: "Mystery" },
    { id: "83", name: "Netorare/NTR" },
    { id: "84", name: "Ninja" },
    { id: "85", name: "Office Workers" },
    { id: "86", name: "Omegaverse" },
    { id: "87", name: "Parody" },
    { id: "88", name: "Philosophical" },
    { id: "89", name: "Police" },
    { id: "90", name: "Post-Apocalyptic" },
    { id: "91", name: "Psychological" },
    { id: "92", name: "Regression" },
    { id: "93", name: "Reincarnation" },
    { id: "94", name: "Reverse Harem" },
    { id: "95", name: "Revenge" },
    { id: "96", name: "Reverse Isekai" },
    { id: "97", name: "Romance" },
    { id: "98", name: "Royal family" },
    { id: "99", name: "Royalty" },
    { id: "100", name: "Samurai" },
    { id: "101", name: "School Life" },
    { id: "102", name: "Sci-Fi" },
    { id: "103", name: "Shoujo ai" },
    { id: "104", name: "Shounen ai" },
    { id: "105", name: "Showbiz" },
    { id: "106", name: "Slice of Life" },
    { id: "107", name: "SM/BDSM/SUB-DOM" },
    { id: "108", name: "Space" },
    { id: "109", name: "Sports" },
    { id: "110", name: "Super Power" },
    { id: "111", name: "Superhero" },
    { id: "112", name: "Supernatural" },
    { id: "113", name: "Survival" },
    { id: "114", name: "Thriller" },
    { id: "115", name: "Time Travel" },
    { id: "116", name: "Tower Climbing" },
    { id: "117", name: "Traditional Games" },
    { id: "118", name: "Tragedy" },
    { id: "119", name: "Transmigration" },
    { id: "120", name: "Vampires" },
    { id: "121", name: "Villainess" },
    { id: "122", name: "Video Games" },
    { id: "123", name: "Virtual Reality" },
    { id: "124", name: "Wuxia" },
    { id: "125", name: "Xianxia" },
    { id: "126", name: "Xuanhuan" },
    { id: "127", name: "Yakuzas" },
    { id: "128", name: "Zombies" },
];
