export const genreOptions = [
    { id: "1", value: "Artbook" },
    { id: "2", value: "Cartoon" },
    { id: "3", value: "Comic" },
    { id: "4", value: "Doujinshi" },
    { id: "5", value: "Imageset" },
    { id: "6", value: "Manga" },
    { id: "7", value: "Manhua" },
    { id: "8", value: "Manhwa" },
    { id: "9", value: "Webtoon" },
    { id: "10", value: "Western" },
    { id: "11", value: "4-Koma" },
    { id: "12", value: "Oneshot" },
    { id: "13", value: "Shoujo" },
    { id: "14", value: "Shounen" },
    { id: "15", value: "Josei" },
    { id: "16", value: "Seinen" },
    { id: "17", value: "Yuri" },
    { id: "18", value: "Yaoi" },
    { id: "19", value: "Bara(ML)" },
    { id: "20", value: "Kodomo(Kid)" },
    { id: "21", value: "Silver & Golden" },
    { id: "22", value: "Non-human" },
    { id: "23", value: "Gore" },
    { id: "24", value: "Bloody" },
    { id: "25", value: "Violence" },
    { id: "26", value: "Ecchi" },
    { id: "27", value: "Adult" },
    { id: "28", value: "Mature" },
    { id: "29", value: "Smut" },
    { id: "30", value: "Hentai" },
    { id: "31", value: "Action" },
    { id: "32", value: "Adaptation" },
    { id: "33", value: "Adventure" },
    { id: "34", value: "Age Gap" },
    { id: "35", value: "Aliens" },
    { id: "36", value: "Animals" },
    { id: "37", value: "Anthology" },
    { id: "38", value: "Beasts" },
    { id: "39", value: "Bodyswap" },
    { id: "40", value: "Boys" },
    { id: "41", value: "Cars" },
    { id: "42", value: "Cheating/Infidelity" },
    { id: "43", value: "Childhood Friends" },
    { id: "44", value: "College life" },
    { id: "45", value: "Comedy" },
    { id: "46", value: "Contest winning" },
    { id: "47", value: "Cooking" },
    { id: "48", value: "Crime" },
    { id: "49", value: "Crossdressing" },
    { id: "50", value: "Delinquents" },
    { id: "51", value: "Dementia" },
    { id: "52", value: "Demons" },
    { id: "53", value: "Drama" },
    { id: "54", value: "Dungeons" },
    { id: "55", value: "Emperor's daughter" },
    { id: "56", value: "Fantasy" },
    { id: "57", value: "Fan-Colored" },
    { id: "58", value: "Fetish" },
    { id: "59", value: "Full Color" },
    { id: "60", value: "Game" },
    { id: "61", value: "Gender Bender" },
    { id: "62", value: "Genderswap" },
    { id: "63", value: "Ghosts" },
    { id: "64", value: "Girls" },
    { id: "65", value: "Gyaru" },
    { id: "66", value: "Harem" },
    { id: "67", value: "Harlequin" },
    { id: "68", value: "Historical" },
    { id: "69", value: "Horror" },
    { id: "70", value: "Incest" },
    { id: "71", value: "Isekai" },
    { id: "72", value: "Kids" },
    { id: "73", value: "Magic" },
    { id: "74", value: "Magical Girls" },
    { id: "75", value: "Martial Arts" },
    { id: "76", value: "Mecha" },
    { id: "77", value: "Medical" },
    { id: "78", value: "Military" },
    { id: "79", value: "Monster Girls" },
    { id: "80", value: "Monsters" },
    { id: "81", value: "Music" },
    { id: "82", value: "Mystery" },
    { id: "83", value: "Netorare/NTR" },
    { id: "84", value: "Ninja" },
    { id: "85", value: "Office Workers" },
    { id: "86", value: "Omegaverse" },
    { id: "87", value: "Parody" },
    { id: "88", value: "Philosophical" },
    { id: "89", value: "Police" },
    { id: "90", value: "Post-Apocalyptic" },
    { id: "91", value: "Psychological" },
    { id: "92", value: "Regression" },
    { id: "93", value: "Reincarnation" },
    { id: "94", value: "Reverse Harem" },
    { id: "95", value: "Revenge" },
    { id: "96", value: "Reverse Isekai" },
    { id: "97", value: "Romance" },
    { id: "98", value: "Royal family" },
    { id: "99", value: "Royalty" },
    { id: "100", value: "Samurai" },
    { id: "101", value: "School Life" },
    { id: "102", value: "Sci-Fi" },
    { id: "103", value: "Shoujo ai" },
    { id: "104", value: "Shounen ai" },
    { id: "105", value: "Showbiz" },
    { id: "106", value: "Slice of Life" },
    { id: "107", value: "SM/BDSM/SUB-DOM" },
    { id: "108", value: "Space" },
    { id: "109", value: "Sports" },
    { id: "110", value: "Super Power" },
    { id: "111", value: "Superhero" },
    { id: "112", value: "Supernatural" },
    { id: "113", value: "Survival" },
    { id: "114", value: "Thriller" },
    { id: "115", value: "Time Travel" },
    { id: "116", value: "Tower Climbing" },
    { id: "117", value: "Traditional Games" },
    { id: "118", value: "Tragedy" },
    { id: "119", value: "Transmigration" },
    { id: "120", value: "Vampires" },
    { id: "121", value: "Villainess" },
    { id: "122", value: "Video Games" },
    { id: "123", value: "Virtual Reality" },
    { id: "124", value: "Wuxia" },
    { id: "125", value: "Xianxia" },
    { id: "126", value: "Xuanhuan" },
    { id: "127", value: "Yakuzas" },
    { id: "128", value: "Zombies" },
];
