// genreOptions.ts

export const genreOptions = [
    { id: "1", value: "Action" },
    { id: "2", value: "Adventure" },
    { id: "3", value: "Comedy" },
    { id: "4", value: "Drama" },
    { id: "5", value: "Fantasy" },
    { id: "6", value: "Martial Arts" },
    { id: "7", value: "Shounen" },
    { id: "8", value: "Horror" },
    { id: "9", value: "Supernatural" },
    { id: "10", value: "Harem" },
    { id: "11", value: "Psychological" },
    { id: "12", value: "Romance" },
    { id: "13", value: "School Life" },
    { id: "14", value: "Shoujo" },
    { id: "15", value: "Mystery" },
    { id: "16", value: "Sci-fi" },
    { id: "17", value: "Seinen" },
    { id: "18", value: "Tragedy" },
    { id: "19", value: "Ecchi" },
    { id: "20", value: "Sports" },
    { id: "21", value: "Slice of Life" },
    { id: "22", value: "Mature" },
    { id: "23", value: "Shoujo Ai" },
    { id: "24", value: "Webtoons" },
    { id: "25", value: "Doujinshi" },
    { id: "26", value: "One Shot" },
    { id: "27", value: "Smut" },
    { id: "28", value: "Yaoi" },
    { id: "29", value: "Josei" },
    { id: "30", value: "Historical" },
    { id: "31", value: "Shounen Ai" },
    { id: "32", value: "Gender Bender" },
    { id: "33", value: "Adult" },
    { id: "34", value: "Yuri" },
    { id: "35", value: "Mecha" },
    { id: "36", value: "Lolicon" },
    { id: "37", value: "Shotacon" },
];
