// genres.ts

export const genres = [
    { id: "1", name: "Action" },
    { id: "2", name: "Adventure" },
    { id: "3", name: "Comedy" },
    { id: "4", name: "Drama" },
    { id: "5", name: "Fantasy" },
    { id: "6", name: "Martial Arts" },
    { id: "7", name: "Shounen" },
    { id: "8", name: "Horror" },
    { id: "9", name: "Supernatural" },
    { id: "10", name: "Harem" },
    { id: "11", name: "Psychological" },
    { id: "12", name: "Romance" },
    { id: "13", name: "School Life" },
    { id: "14", name: "Shoujo" },
    { id: "15", name: "Mystery" },
    { id: "16", name: "Sci-fi" },
    { id: "17", name: "Seinen" },
    { id: "18", name: "Tragedy" },
    { id: "19", name: "Ecchi" },
    { id: "20", name: "Sports" },
    { id: "21", name: "Slice of Life" },
    { id: "22", name: "Mature" },
    { id: "23", name: "Shoujo Ai" },
    { id: "24", name: "Webtoons" },
    { id: "25", name: "Doujinshi" },
    { id: "26", name: "One Shot" },
    { id: "27", name: "Smut" },
    { id: "28", name: "Yaoi" },
    { id: "29", name: "Josei" },
    { id: "30", name: "Historical" },
    { id: "31", name: "Shounen Ai" },
    { id: "32", name: "Gender Bender" },
    { id: "33", name: "Adult" },
    { id: "34", name: "Yuri" },
    { id: "35", name: "Mecha" },
    { id: "36", name: "Lolicon" },
    { id: "37", name: "Shotacon" },
];
